### PR TITLE
It would be helpful to include context_info in the BoxAPIException

### PR DESCRIPTION
**Pull request by samkuehn**
For example when trying you create a folder that already exists you will get back a list of conflicts in the context_info in the response.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @samkuehn, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by samkuehn** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @samkuehn has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by aptxkid** [comment]
@samkuehn The change looks great! The only thing I am not sure about is that `context_info` is not in the content API documentation, https://box-content.readme.io/#errors. Maybe we should add it to the documentation if it can be part of the contract.

**Comment by samkuehn** [comment]
@aptxkid That seems like a good idea. `context_info` is mentioned in this blog post https://www.box.com/blog/get-developer-hugs-with-rich-error-handling-in-your-api/

**Comment by samkuehn** [comment]
`context_info` seems to be returned on errors other than just `item_name_in_use`.  For example if you try and create a folder with an unsupported special character you get error code `item_name_invalid` and the `context_info` looks like this:

Names cannot contain non-printable ASCII, / or \, leading or trailing whitespace. The special names "." or ".." are also unsupported.

**Comment by aptxkid** [comment]
Thanks @samkuehn ! I am trying to make the change on documentation. As soon as it's done, I can merge this change.

**Comment by aptxkid** [comment]
@samkuehn Changing the doc is taking longer than I wanted. I am going to merge this first. :smile:

**Comment by aptxkid** [comment]
@samkuehn The documentation is updated with `context_info`, https://box-content.readme.io/#errors.  :smile:

**Pull request merged**
