### PR TITLE
Identifier for the store tokens method

### PR DESCRIPTION
**Pull request by Tusky**
Adds ability to add an extra identifier, so it can be saved to the database with that. My change allows backwards compatibility, for those who doesn't need that feature.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @Tusky, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by Tusky** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @Tusky has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by jmoldow** [comment]
This change is unnecessary for the SDK (and also seems specific to whatever you're doing).

You can accomplish the same exact thing without an SDK change:

```python
from functools import partial

def store_tokens(access_token, refresh_token, record_identifier):
  ...

oauth = OAuth2(..., store_tokens=partial(store_tokens, record_identifier=u'identifier'))
```

**Comment by Tusky** [comment]
Thanks, didn't know about partial and yeah in that case this is pointless :+1:

**Pull request closed without merging**
