### PR TITLE
Feature/optional rate limiter

### PR DESCRIPTION
**Pull request by dtrodger**
- Add's rate limited context manager class to boxsdk.client.rate_limiter.RateLimiter
- Adds rate_limited (bool), rate_limit (int) to boxsdk.client.client.Client.__init__ kwargs. If rate_limited = True, sets Client instance attribute _rate_limiter = to a RateLimiter instance with the limit per seconds set = rate_limit kwarg.
- Updates boxsdk.client.client.Client.make_request to call the RateLimiter if Client._rate_limiter is not None.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @dtrodger, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by dtrodger** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @dtrodger has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by dtrodger** [comment]
The latest commit will pass your linter

**Comment by dtrodger** [comment]
Context on why this is useful. I've been on a few Box Consutling engagements where clients were spending lots of money on Platform api calls and no educated on our rate limits, so sometimes 50%+ of the calls they pay for are 429s. This is a simple workaround vs. The app user pooling model we traditionally recommend.

**Comment by PJSimon** [comment]
@dtrodger Thanks for sending this in, we'll take a look (SDK-1323) ASAP!

**Comment by sujaygarlanka** [comment]
@boxdave putting up another PR for this.

**Pull request closed without merging**
