### PR TITLE
Changed base_object so it can be compared to None object

### PR DESCRIPTION
**Pull request by jhogg**
Changed __eq__ comparison to allow an object to be compared to None in addition to another object by id.   The current code requires that it be compared against another instantiated object.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @jhogg, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by jhogg** [comment]
CLA Signed

**Comment by boxcla** [comment]
Verified that @jhogg has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by jmoldow** [comment]
Thanks for the pull request.

However, it would be more flexible to do something like

```python
if not isinstance(other, BaseObject):
    return NotImplemented
...
```

There are other bugs with `__eq__` as well, which I've documented in #163. I'll be opening up a new PR with these fixes.

**Pull request closed without merging**
