### PR TITLE
Fixing some typos in README.rst

### PR DESCRIPTION
**Pull request by bhh1988**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @bhh1988, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by bhh1988** [comment]
CLA signed

**Comment by boxcla** [comment]
I couldn't find a signed CLA for @bhh1988. Can you please try again?

**Comment by bhh1988** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @bhh1988 has just signed the CLA. Thanks, and we look forward to your contribution.

**Pull request merged**
