### PR TITLE
Add an example for retrieving both a folder and file name.

### PR DESCRIPTION
**Pull request by djgoku**
Hope this help others while trying to get folder and file name strings.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @djgoku, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by aptxkid** [comment]
Awesome! Thanks, @djgoku

**Comment by aptxkid** [comment]
@djgoku, apparently, I got too excited and merged your change before you sign the CLA. I am reverting the change. Would you please open another PR for the same change? I will merge the change after you sign the CLA. Sorry for the inconvenience. Thanks for your contribution!

**Comment by djgoku** [comment]
@aptxkid I filled it out again just now. Did you mind looking to see if my signed CLA is saved in the Google form?

**Comment by aptxkid** [comment]
Thanks, @djgoku! I think you need to add a comment to the pull request saying, "CLA signed". And the @boxcla bot will do the verification. (e.g. https://github.com/box/flaky/pull/21)

**Pull request merged**
