### PR TITLE
Add task and comment and task assignment api

### PR DESCRIPTION
**Pull request by liketic**
Hi, 

When I ingest data from box api with python sdk, I found there is no comment and task related api, so I added these APIs in this PR. Happy to hear your comments. Thanks.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @likel has signed the CLA. Thanks for the pull request!

**Comment by jmoldow** [comment]
Thanks for the pull request!

You're going to need to merge master in order to bring your branch up-to-date.

Please add entrypoints for all of these in `boxsdk/client/client.py`. E.g.

```python
def comment(self, comment_id):
    return self.translator.translate('comment')(session=self._session, object_id=comment_id)
```

Also, as I mentioned in https://github.com/box/box-python-sdk/issues/153#issuecomment-236063398 , we haven't yet defined how we want to define a unified API for all paging endpoints. You've defined a few paging endpoints (though, unfortunately, it doesn't look like they are explicitly documented as being paging endpoints in the API reference documentation). I'd prefer if we removed these for now, that way we don't have to make a breaking SDK change later. You should be able to easily define these in your own SDK subclasses, and use them in your application.

**Comment by likel** [comment]
@jmoldow Thanks for your reply. I understand your concern. Thanks.

**Comment by liketic** [comment]
Close this cause no one need it.

**Pull request closed without merging**
